ImageSize = 84
Ncouleur = 4

POPULATION_SIZE = 20
BATTLE_PER_GENOM = 5

action_space = ["up", "down", "left", "right", "a", "b"]

POKEMON_ID_TO_NAME= {
    0: "none",
    1: "rhydon",
    2: "kangaskhan",
    3: "nidoranm",
    4: "clefairy",
    5: "spearow",
    6: "voltorb",
    7: "nidoking",
    8: "slowbro",
    9: "ivysaur",
    10: "exeggutor",
    11: "lickitung",
    12: "exeggcute",
    13: "grimer",
    14: "gengar",
    15: "nidoranf",
    16: "nidoqueen",
    17: "cubone",
    18: "rhyhorn",
    19: "lapras",
    20: "arcanine",
    21: "mew",
    22: "gyarados",
    23: "shellder",
    24: "tentacool",
    25: "gastly",
    26: "scyther",
    27: "staryu",
    28: "blastoise",
    29: "pinsir",
    30: "tangela",
    31: "missingno",
    32: "missingno",
    33: "growlithe",
    34: "onix",
    35: "fearow",
    36: "pidgey",
    37: "slowpoke",
    38: "kadabra",
    39: "graveler",
    40: "chansey",
    41: "machoke",
    42: "mr.mime",
    43: "hitmonlee",
    44: "hitmonchan",
    45: "arbok",
    46: "parasect",
    47: "psyduck",
    48: "drowzee",
    49: "golem",
    50: "missingno",
    51: "magmar",
    52: "missingno",
    53: "electabuzz",
    54: "magneton",
    55: "koffing",
    56: "missingno",
    57: "mankey",
    58: "seel",
    59: "diglett",
    60: "tauros",
    61: "missingno",
    62: "missingno",
    63: "missingno",
    64: "farfetchd",
    65: "venonat",
    66: "dragonite",
    67: "missingno",
    68: "missingno",
    69: "missingno",
    70: "doduo",
    71: "poliwag",
    72: "jynx",
    73: "moltres",
    74: "articuno",
    75: "zapdos",
    76: "ditto",
    77: "meowth",
    78: "krabby",
    79: "missingno",
    80: "missingno",
    81: "missingno",
    82: "vulpix",
    83: "ninetales",
    84: "pikachu",
    85: "raichu",
    86: "missingno",
    87: "missingno",
    88: "dratini",
    89: "dragonair",
    90: "kabuto",
    91: "kabutops",
    92: "horsea",
    93: "seadra",
    94: "missingno",
    95: "missingno",
    96: "sandshrew",
    97: "sandslash",
    98: "omanyte",
    99: "omastar",
    100: "jigglypuff",
    101: "wigglytuff",
    102: "eevee",
    103: "flareon",
    104: "jolteon",
    105: "vaporeon",
    106: "machop",
    107: "zubat",
    108: "ekans",
    109: "paras",
    110: "poliwhirl",
    111: "poliwrath",
    112: "weedle",
    113: "kakuna",
    114: "beedrill",
    115: "missingno",
    116: "dodrio",
    117: "primeape",
    118: "dugtrio",
    119: "venomoth",
    120: "dewgong",
    121: "missingno",
    122: "missingno",
    123: "caterpie",
    124: "metapod",
    125: "butterfree",
    126: "machamp",
    127: "missingno",
    128: "golduck",
    129: "hypno",
    130: "golbat",
    131: "mewtwo",
    132: "snorlax",
    133: "magikarp",
    134: "missingno",
    135: "missingno",
    136: "muk",
    137: "missingno",
    138: "kingler",
    139: "cloyster",
    140: "missingno",
    141: "electrode",
    142: "clefable",
    143: "weezing",
    144: "persian",
    145: "marowak",
    146: "missingno",
    147: "haunter",
    148: "abra",
    149: "alakazam",
    150: "pidgeotto",
    151: "pidgeot",
    152: "starmie",
    153: "bulbasaur",
    154: "venusaur",
    155: "tentacruel",
    156: "missingno",
    157: "goldeen",
    158: "seaking",
    159: "missingno",
    160: "missingno",
    161: "missingno",
    162: "missingno",
    163: "ponyta",
    164: "rapidash",
    165: "rattata",
    166: "raticate",
    167: "nidorino",
    168: "nidorina",
    169: "geodude",
    170: "porygon",
    171: "aerodactyl",
    172: "missingno",
    173: "magnemite",
    174: "missingno",
    175: "missingno",
    176: "charmander",
    177: "squirtle",
    178: "charmeleon",
    179: "wartortle",
    180: "charizard",
    181: "missingno",
    182: "missingno",
    183: "missingno",
    184: "missingno",
    185: "oddish",
    186: "gloom",
    187: "vileplume",
    188: "bellsprout",
    189: "weepinbell",
    190: "victreebel"
}

POKEMON_BASE_STATS = {
    "none": {'hp':-1, 'atk':-1 , 'def': -1, 'spd':-1, 'spc':-1, 'type1':'BIRD', 'type2':'BIRD'},
    "abra": {'hp': 25, 'atk': 20, 'def': 15, 'spd': 90, 'spc': 105, 'type1': 'PSYCHIC_TYPE', 'type2': 'PSYCHIC_TYPE'},      
    "aerodactyl": {'hp': 80, 'atk': 105, 'def': 65, 'spd': 130, 'spc': 60, 'type1': 'ROCK', 'type2': 'FLYING'},
    "alakazam": {'hp': 55, 'atk': 50, 'def': 45, 'spd': 120, 'spc': 135, 'type1': 'PSYCHIC_TYPE', 'type2': 'PSYCHIC_TYPE'}, 
    "arbok": {'hp': 60, 'atk': 85, 'def': 69, 'spd': 80, 'spc': 65, 'type1': 'POISON', 'type2': 'POISON'},
    "arcanine": {'hp': 90, 'atk': 110, 'def': 80, 'spd': 95, 'spc': 80, 'type1': 'FIRE', 'type2': 'FIRE'},
    "articuno": {'hp': 90, 'atk': 85, 'def': 100, 'spd': 85, 'spc': 125, 'type1': 'ICE', 'type2': 'FLYING'},
    "beedrill": {'hp': 65, 'atk': 80, 'def': 40, 'spd': 75, 'spc': 45, 'type1': 'BUG', 'type2': 'POISON'},
    "bellsprout": {'hp': 50, 'atk': 75, 'def': 35, 'spd': 40, 'spc': 70, 'type1': 'GRASS', 'type2': 'POISON'},
    "blastoise": {'hp': 79, 'atk': 83, 'def': 100, 'spd': 78, 'spc': 85, 'type1': 'WATER', 'type2': 'WATER'},
    "bulbasaur": {'hp': 45, 'atk': 49, 'def': 49, 'spd': 45, 'spc': 65, 'type1': 'GRASS', 'type2': 'POISON'},
    "butterfree": {'hp': 60, 'atk': 45, 'def': 50, 'spd': 70, 'spc': 80, 'type1': 'BUG', 'type2': 'FLYING'},
    "caterpie": {'hp': 45, 'atk': 30, 'def': 35, 'spd': 45, 'spc': 20, 'type1': 'BUG', 'type2': 'BUG'},
    "chansey": {'hp': 250, 'atk': 5, 'def': 5, 'spd': 50, 'spc': 105, 'type1': 'NORMAL', 'type2': 'NORMAL'},
    "charizard": {'hp': 78, 'atk': 84, 'def': 78, 'spd': 100, 'spc': 85, 'type1': 'FIRE', 'type2': 'FLYING'},
    "charmander": {'hp': 39, 'atk': 52, 'def': 43, 'spd': 65, 'spc': 50, 'type1': 'FIRE', 'type2': 'FIRE'},
    "charmeleon": {'hp': 58, 'atk': 64, 'def': 58, 'spd': 80, 'spc': 65, 'type1': 'FIRE', 'type2': 'FIRE'},
    "clefable": {'hp': 95, 'atk': 70, 'def': 73, 'spd': 60, 'spc': 85, 'type1': 'NORMAL', 'type2': 'NORMAL'},
    "clefairy": {'hp': 70, 'atk': 45, 'def': 48, 'spd': 35, 'spc': 60, 'type1': 'NORMAL', 'type2': 'NORMAL'},
    "cloyster": {'hp': 50, 'atk': 95, 'def': 180, 'spd': 70, 'spc': 85, 'type1': 'WATER', 'type2': 'ICE'},
    "cubone": {'hp': 50, 'atk': 50, 'def': 95, 'spd': 35, 'spc': 40, 'type1': 'GROUND', 'type2': 'GROUND'},
    "dewgong": {'hp': 90, 'atk': 70, 'def': 80, 'spd': 70, 'spc': 95, 'type1': 'WATER', 'type2': 'ICE'},
    "diglett": {'hp': 10, 'atk': 55, 'def': 25, 'spd': 95, 'spc': 45, 'type1': 'GROUND', 'type2': 'GROUND'},
    "ditto": {'hp': 48, 'atk': 48, 'def': 48, 'spd': 48, 'spc': 48, 'type1': 'NORMAL', 'type2': 'NORMAL'},
    "dodrio": {'hp': 60, 'atk': 110, 'def': 70, 'spd': 100, 'spc': 60, 'type1': 'NORMAL', 'type2': 'FLYING'},
    "doduo": {'hp': 35, 'atk': 85, 'def': 45, 'spd': 75, 'spc': 35, 'type1': 'NORMAL', 'type2': 'FLYING'},
    "dragonair": {'hp': 61, 'atk': 84, 'def': 65, 'spd': 70, 'spc': 70, 'type1': 'DRAGON', 'type2': 'DRAGON'},
    "dragonite": {'hp': 91, 'atk': 134, 'def': 95, 'spd': 80, 'spc': 100, 'type1': 'DRAGON', 'type2': 'FLYING'},
    "dratini": {'hp': 41, 'atk': 64, 'def': 45, 'spd': 50, 'spc': 50, 'type1': 'DRAGON', 'type2': 'DRAGON'},
    "drowzee": {'hp': 60, 'atk': 48, 'def': 45, 'spd': 42, 'spc': 90, 'type1': 'PSYCHIC_TYPE', 'type2': 'PSYCHIC_TYPE'},    
    "dugtrio": {'hp': 35, 'atk': 80, 'def': 50, 'spd': 120, 'spc': 70, 'type1': 'GROUND', 'type2': 'GROUND'},
    "eevee": {'hp': 55, 'atk': 55, 'def': 50, 'spd': 55, 'spc': 65, 'type1': 'NORMAL', 'type2': 'NORMAL'},
    "ekans": {'hp': 35, 'atk': 60, 'def': 44, 'spd': 55, 'spc': 40, 'type1': 'POISON', 'type2': 'POISON'},
    "electabuzz": {'hp': 65, 'atk': 83, 'def': 57, 'spd': 105, 'spc': 85, 'type1': 'ELECTRIC', 'type2': 'ELECTRIC'},        
    "electrode": {'hp': 60, 'atk': 50, 'def': 70, 'spd': 140, 'spc': 80, 'type1': 'ELECTRIC', 'type2': 'ELECTRIC'},
    "exeggcute": {'hp': 60, 'atk': 40, 'def': 80, 'spd': 40, 'spc': 60, 'type1': 'GRASS', 'type2': 'PSYCHIC_TYPE'},
    "exeggutor": {'hp': 95, 'atk': 95, 'def': 85, 'spd': 55, 'spc': 125, 'type1': 'GRASS', 'type2': 'PSYCHIC_TYPE'},        
    "farfetchd": {'hp': 52, 'atk': 65, 'def': 55, 'spd': 60, 'spc': 58, 'type1': 'NORMAL', 'type2': 'FLYING'},
    "fearow": {'hp': 65, 'atk': 90, 'def': 65, 'spd': 100, 'spc': 61, 'type1': 'NORMAL', 'type2': 'FLYING'},
    "flareon": {'hp': 65, 'atk': 130, 'def': 60, 'spd': 65, 'spc': 110, 'type1': 'FIRE', 'type2': 'FIRE'},
    "gastly": {'hp': 30, 'atk': 35, 'def': 30, 'spd': 80, 'spc': 100, 'type1': 'GHOST', 'type2': 'POISON'},
    "gengar": {'hp': 60, 'atk': 65, 'def': 60, 'spd': 110, 'spc': 130, 'type1': 'GHOST', 'type2': 'POISON'},
    "geodude": {'hp': 40, 'atk': 80, 'def': 100, 'spd': 20, 'spc': 30, 'type1': 'ROCK', 'type2': 'GROUND'},
    "gloom": {'hp': 60, 'atk': 65, 'def': 70, 'spd': 40, 'spc': 85, 'type1': 'GRASS', 'type2': 'POISON'},
    "golbat": {'hp': 75, 'atk': 80, 'def': 70, 'spd': 90, 'spc': 75, 'type1': 'POISON', 'type2': 'FLYING'},
    "goldeen": {'hp': 45, 'atk': 67, 'def': 60, 'spd': 63, 'spc': 50, 'type1': 'WATER', 'type2': 'WATER'},
    "golduck": {'hp': 80, 'atk': 82, 'def': 78, 'spd': 85, 'spc': 80, 'type1': 'WATER', 'type2': 'WATER'},
    "golem": {'hp': 80, 'atk': 110, 'def': 130, 'spd': 45, 'spc': 55, 'type1': 'ROCK', 'type2': 'GROUND'},
    "graveler": {'hp': 55, 'atk': 95, 'def': 115, 'spd': 35, 'spc': 45, 'type1': 'ROCK', 'type2': 'GROUND'},
    "grimer": {'hp': 80, 'atk': 80, 'def': 50, 'spd': 25, 'spc': 40, 'type1': 'POISON', 'type2': 'POISON'},
    "growlithe": {'hp': 55, 'atk': 70, 'def': 45, 'spd': 60, 'spc': 50, 'type1': 'FIRE', 'type2': 'FIRE'},
    "gyarados": {'hp': 95, 'atk': 125, 'def': 79, 'spd': 81, 'spc': 100, 'type1': 'WATER', 'type2': 'FLYING'},
    "haunter": {'hp': 45, 'atk': 50, 'def': 45, 'spd': 95, 'spc': 115, 'type1': 'GHOST', 'type2': 'POISON'},
    "hitmonchan": {'hp': 50, 'atk': 105, 'def': 79, 'spd': 76, 'spc': 35, 'type1': 'FIGHTING', 'type2': 'FIGHTING'},        
    "hitmonlee": {'hp': 50, 'atk': 120, 'def': 53, 'spd': 87, 'spc': 35, 'type1': 'FIGHTING', 'type2': 'FIGHTING'},
    "horsea": {'hp': 30, 'atk': 40, 'def': 70, 'spd': 60, 'spc': 70, 'type1': 'WATER', 'type2': 'WATER'},
    "hypno": {'hp': 85, 'atk': 73, 'def': 70, 'spd': 67, 'spc': 115, 'type1': 'PSYCHIC_TYPE', 'type2': 'PSYCHIC_TYPE'},     
    "ivysaur": {'hp': 60, 'atk': 62, 'def': 63, 'spd': 60, 'spc': 80, 'type1': 'GRASS', 'type2': 'POISON'},
    "jigglypuff": {'hp': 115, 'atk': 45, 'def': 20, 'spd': 20, 'spc': 25, 'type1': 'NORMAL', 'type2': 'NORMAL'},
    "jolteon": {'hp': 65, 'atk': 65, 'def': 60, 'spd': 130, 'spc': 110, 'type1': 'ELECTRIC', 'type2': 'ELECTRIC'},
    "jynx": {'hp': 65, 'atk': 50, 'def': 35, 'spd': 95, 'spc': 95, 'type1': 'ICE', 'type2': 'PSYCHIC_TYPE'},
    "kabuto": {'hp': 30, 'atk': 80, 'def': 90, 'spd': 55, 'spc': 45, 'type1': 'ROCK', 'type2': 'WATER'},
    "kabutops": {'hp': 60, 'atk': 115, 'def': 105, 'spd': 80, 'spc': 70, 'type1': 'ROCK', 'type2': 'WATER'},
    "kadabra": {'hp': 40, 'atk': 35, 'def': 30, 'spd': 105, 'spc': 120, 'type1': 'PSYCHIC_TYPE', 'type2': 'PSYCHIC_TYPE'},  
    "kakuna": {'hp': 45, 'atk': 25, 'def': 50, 'spd': 35, 'spc': 25, 'type1': 'BUG', 'type2': 'POISON'},
    "kangaskhan": {'hp': 105, 'atk': 95, 'def': 80, 'spd': 90, 'spc': 40, 'type1': 'NORMAL', 'type2': 'NORMAL'},
    "kingler": {'hp': 55, 'atk': 130, 'def': 115, 'spd': 75, 'spc': 50, 'type1': 'WATER', 'type2': 'WATER'},
    "koffing": {'hp': 40, 'atk': 65, 'def': 95, 'spd': 35, 'spc': 60, 'type1': 'POISON', 'type2': 'POISON'},
    "krabby": {'hp': 30, 'atk': 105, 'def': 90, 'spd': 50, 'spc': 25, 'type1': 'WATER', 'type2': 'WATER'},
    "lapras": {'hp': 130, 'atk': 85, 'def': 80, 'spd': 60, 'spc': 95, 'type1': 'WATER', 'type2': 'ICE'},
    "lickitung": {'hp': 90, 'atk': 55, 'def': 75, 'spd': 30, 'spc': 60, 'type1': 'NORMAL', 'type2': 'NORMAL'},
    "machamp": {'hp': 90, 'atk': 130, 'def': 80, 'spd': 55, 'spc': 65, 'type1': 'FIGHTING', 'type2': 'FIGHTING'},
    "machoke": {'hp': 80, 'atk': 100, 'def': 70, 'spd': 45, 'spc': 50, 'type1': 'FIGHTING', 'type2': 'FIGHTING'},
    "machop": {'hp': 70, 'atk': 80, 'def': 50, 'spd': 35, 'spc': 35, 'type1': 'FIGHTING', 'type2': 'FIGHTING'},
    "magikarp": {'hp': 20, 'atk': 10, 'def': 55, 'spd': 80, 'spc': 20, 'type1': 'WATER', 'type2': 'WATER'},
    "magmar": {'hp': 65, 'atk': 95, 'def': 57, 'spd': 93, 'spc': 85, 'type1': 'FIRE', 'type2': 'FIRE'},
    "magnemite": {'hp': 25, 'atk': 35, 'def': 70, 'spd': 45, 'spc': 95, 'type1': 'ELECTRIC', 'type2': 'ELECTRIC'},
    "magneton": {'hp': 50, 'atk': 60, 'def': 95, 'spd': 70, 'spc': 120, 'type1': 'ELECTRIC', 'type2': 'ELECTRIC'},
    "mankey": {'hp': 40, 'atk': 80, 'def': 35, 'spd': 70, 'spc': 35, 'type1': 'FIGHTING', 'type2': 'FIGHTING'},
    "marowak": {'hp': 60, 'atk': 80, 'def': 110, 'spd': 45, 'spc': 50, 'type1': 'GROUND', 'type2': 'GROUND'},
    "meowth": {'hp': 40, 'atk': 45, 'def': 35, 'spd': 90, 'spc': 40, 'type1': 'NORMAL', 'type2': 'NORMAL'},
    "metapod": {'hp': 50, 'atk': 20, 'def': 55, 'spd': 30, 'spc': 25, 'type1': 'BUG', 'type2': 'BUG'},
    "mew": {'hp': 100, 'atk': 100, 'def': 100, 'spd': 100, 'spc': 100, 'type1': 'PSYCHIC_TYPE', 'type2': 'PSYCHIC_TYPE'},   
    "mewtwo": {'hp': 106, 'atk': 110, 'def': 90, 'spd': 130, 'spc': 154, 'type1': 'PSYCHIC_TYPE', 'type2': 'PSYCHIC_TYPE'}, 
    "moltres": {'hp': 90, 'atk': 100, 'def': 90, 'spd': 90, 'spc': 125, 'type1': 'FIRE', 'type2': 'FLYING'},
    "mr.mime": {'hp': 40, 'atk': 45, 'def': 65, 'spd': 90, 'spc': 100, 'type1': 'PSYCHIC_TYPE', 'type2': 'PSYCHIC_TYPE'},    
    "muk": {'hp': 105, 'atk': 105, 'def': 75, 'spd': 50, 'spc': 65, 'type1': 'POISON', 'type2': 'POISON'},
    "nidoking": {'hp': 81, 'atk': 92, 'def': 77, 'spd': 85, 'spc': 75, 'type1': 'POISON', 'type2': 'GROUND'},
    "nidoqueen": {'hp': 90, 'atk': 82, 'def': 87, 'spd': 76, 'spc': 75, 'type1': 'POISON', 'type2': 'GROUND'},
    "nidoranf": {'hp': 55, 'atk': 47, 'def': 52, 'spd': 41, 'spc': 40, 'type1': 'POISON', 'type2': 'POISON'},
    "nidoranm": {'hp': 46, 'atk': 57, 'def': 40, 'spd': 50, 'spc': 40, 'type1': 'POISON', 'type2': 'POISON'},
    "nidorina": {'hp': 70, 'atk': 62, 'def': 67, 'spd': 56, 'spc': 55, 'type1': 'POISON', 'type2': 'POISON'},
    "nidorino": {'hp': 61, 'atk': 72, 'def': 57, 'spd': 65, 'spc': 55, 'type1': 'POISON', 'type2': 'POISON'},
    "ninetales": {'hp': 73, 'atk': 76, 'def': 75, 'spd': 100, 'spc': 100, 'type1': 'FIRE', 'type2': 'FIRE'},
    "oddish": {'hp': 45, 'atk': 50, 'def': 55, 'spd': 30, 'spc': 75, 'type1': 'GRASS', 'type2': 'POISON'},
    "omanyte": {'hp': 35, 'atk': 40, 'def': 100, 'spd': 35, 'spc': 90, 'type1': 'ROCK', 'type2': 'WATER'},
    "omastar": {'hp': 70, 'atk': 60, 'def': 125, 'spd': 55, 'spc': 115, 'type1': 'ROCK', 'type2': 'WATER'},
    "onix": {'hp': 35, 'atk': 45, 'def': 160, 'spd': 70, 'spc': 30, 'type1': 'ROCK', 'type2': 'GROUND'},
    "paras": {'hp': 35, 'atk': 70, 'def': 55, 'spd': 25, 'spc': 55, 'type1': 'BUG', 'type2': 'GRASS'},
    "parasect": {'hp': 60, 'atk': 95, 'def': 80, 'spd': 30, 'spc': 80, 'type1': 'BUG', 'type2': 'GRASS'},
    "persian": {'hp': 65, 'atk': 70, 'def': 60, 'spd': 115, 'spc': 65, 'type1': 'NORMAL', 'type2': 'NORMAL'},
    "pidgeot": {'hp': 83, 'atk': 80, 'def': 75, 'spd': 91, 'spc': 70, 'type1': 'NORMAL', 'type2': 'FLYING'},
    "pidgeotto": {'hp': 63, 'atk': 60, 'def': 55, 'spd': 71, 'spc': 50, 'type1': 'NORMAL', 'type2': 'FLYING'},
    "pidgey": {'hp': 40, 'atk': 45, 'def': 40, 'spd': 56, 'spc': 35, 'type1': 'NORMAL', 'type2': 'FLYING'},
    "pikachu": {'hp': 35, 'atk': 55, 'def': 30, 'spd': 90, 'spc': 50, 'type1': 'ELECTRIC', 'type2': 'ELECTRIC'},
    "pinsir": {'hp': 65, 'atk': 125, 'def': 100, 'spd': 85, 'spc': 55, 'type1': 'BUG', 'type2': 'BUG'},
    "poliwag": {'hp': 40, 'atk': 50, 'def': 40, 'spd': 90, 'spc': 40, 'type1': 'WATER', 'type2': 'WATER'},
    "poliwhirl": {'hp': 65, 'atk': 65, 'def': 65, 'spd': 90, 'spc': 50, 'type1': 'WATER', 'type2': 'WATER'},
    "poliwrath": {'hp': 90, 'atk': 85, 'def': 95, 'spd': 70, 'spc': 70, 'type1': 'WATER', 'type2': 'FIGHTING'},
    "ponyta": {'hp': 50, 'atk': 85, 'def': 55, 'spd': 90, 'spc': 65, 'type1': 'FIRE', 'type2': 'FIRE'},
    "porygon": {'hp': 65, 'atk': 60, 'def': 70, 'spd': 40, 'spc': 75, 'type1': 'NORMAL', 'type2': 'NORMAL'},
    "primeape": {'hp': 65, 'atk': 105, 'def': 60, 'spd': 95, 'spc': 60, 'type1': 'FIGHTING', 'type2': 'FIGHTING'},
    "psyduck": {'hp': 50, 'atk': 52, 'def': 48, 'spd': 55, 'spc': 50, 'type1': 'WATER', 'type2': 'WATER'},
    "raichu": {'hp': 60, 'atk': 90, 'def': 55, 'spd': 100, 'spc': 90, 'type1': 'ELECTRIC', 'type2': 'ELECTRIC'},
    "rapidash": {'hp': 65, 'atk': 100, 'def': 70, 'spd': 105, 'spc': 80, 'type1': 'FIRE', 'type2': 'FIRE'},
    "raticate": {'hp': 55, 'atk': 81, 'def': 60, 'spd': 97, 'spc': 50, 'type1': 'NORMAL', 'type2': 'NORMAL'},
    "rattata": {'hp': 30, 'atk': 56, 'def': 35, 'spd': 72, 'spc': 25, 'type1': 'NORMAL', 'type2': 'NORMAL'},
    "rhydon": {'hp': 105, 'atk': 130, 'def': 120, 'spd': 40, 'spc': 45, 'type1': 'GROUND', 'type2': 'ROCK'},
    "rhyhorn": {'hp': 80, 'atk': 85, 'def': 95, 'spd': 25, 'spc': 30, 'type1': 'GROUND', 'type2': 'ROCK'},
    "sandshrew": {'hp': 50, 'atk': 75, 'def': 85, 'spd': 40, 'spc': 30, 'type1': 'GROUND', 'type2': 'GROUND'},
    "sandslash": {'hp': 75, 'atk': 100, 'def': 110, 'spd': 65, 'spc': 55, 'type1': 'GROUND', 'type2': 'GROUND'},
    "scyther": {'hp': 70, 'atk': 110, 'def': 80, 'spd': 105, 'spc': 55, 'type1': 'BUG', 'type2': 'FLYING'},
    "seadra": {'hp': 55, 'atk': 65, 'def': 95, 'spd': 85, 'spc': 95, 'type1': 'WATER', 'type2': 'WATER'},
    "seaking": {'hp': 80, 'atk': 92, 'def': 65, 'spd': 68, 'spc': 80, 'type1': 'WATER', 'type2': 'WATER'},
    "seel": {'hp': 65, 'atk': 45, 'def': 55, 'spd': 45, 'spc': 70, 'type1': 'WATER', 'type2': 'WATER'},
    "shellder": {'hp': 30, 'atk': 65, 'def': 100, 'spd': 40, 'spc': 45, 'type1': 'WATER', 'type2': 'WATER'},
    "slowbro": {'hp': 95, 'atk': 75, 'def': 110, 'spd': 30, 'spc': 80, 'type1': 'WATER', 'type2': 'PSYCHIC_TYPE'},
    "slowpoke": {'hp': 90, 'atk': 65, 'def': 65, 'spd': 15, 'spc': 40, 'type1': 'WATER', 'type2': 'PSYCHIC_TYPE'},
    "snorlax": {'hp': 160, 'atk': 110, 'def': 65, 'spd': 30, 'spc': 65, 'type1': 'NORMAL', 'type2': 'NORMAL'},
    "spearow": {'hp': 40, 'atk': 60, 'def': 30, 'spd': 70, 'spc': 31, 'type1': 'NORMAL', 'type2': 'FLYING'},
    "squirtle": {'hp': 44, 'atk': 48, 'def': 65, 'spd': 43, 'spc': 50, 'type1': 'WATER', 'type2': 'WATER'},
    "starmie": {'hp': 60, 'atk': 75, 'def': 85, 'spd': 115, 'spc': 100, 'type1': 'WATER', 'type2': 'PSYCHIC_TYPE'},
    "staryu": {'hp': 30, 'atk': 45, 'def': 55, 'spd': 85, 'spc': 70, 'type1': 'WATER', 'type2': 'WATER'},
    "tangela": {'hp': 65, 'atk': 55, 'def': 115, 'spd': 60, 'spc': 100, 'type1': 'GRASS', 'type2': 'GRASS'},
    "tauros": {'hp': 75, 'atk': 100, 'def': 95, 'spd': 110, 'spc': 70, 'type1': 'NORMAL', 'type2': 'NORMAL'},
    "tentacool": {'hp': 40, 'atk': 40, 'def': 35, 'spd': 70, 'spc': 100, 'type1': 'WATER', 'type2': 'POISON'},
    "tentacruel": {'hp': 80, 'atk': 70, 'def': 65, 'spd': 100, 'spc': 120, 'type1': 'WATER', 'type2': 'POISON'},
    "vaporeon": {'hp': 130, 'atk': 65, 'def': 60, 'spd': 65, 'spc': 110, 'type1': 'WATER', 'type2': 'WATER'},
    "venomoth": {'hp': 70, 'atk': 65, 'def': 60, 'spd': 90, 'spc': 90, 'type1': 'BUG', 'type2': 'POISON'},
    "venonat": {'hp': 60, 'atk': 55, 'def': 50, 'spd': 45, 'spc': 40, 'type1': 'BUG', 'type2': 'POISON'},
    "venusaur": {'hp': 80, 'atk': 82, 'def': 83, 'spd': 80, 'spc': 100, 'type1': 'GRASS', 'type2': 'POISON'},
    "victreebel": {'hp': 80, 'atk': 105, 'def': 65, 'spd': 70, 'spc': 100, 'type1': 'GRASS', 'type2': 'POISON'},
    "vileplume": {'hp': 75, 'atk': 80, 'def': 85, 'spd': 50, 'spc': 100, 'type1': 'GRASS', 'type2': 'POISON'},
    "voltorb": {'hp': 40, 'atk': 30, 'def': 50, 'spd': 100, 'spc': 55, 'type1': 'ELECTRIC', 'type2': 'ELECTRIC'},
    "vulpix": {'hp': 38, 'atk': 41, 'def': 40, 'spd': 65, 'spc': 65, 'type1': 'FIRE', 'type2': 'FIRE'},
    "wartortle": {'hp': 59, 'atk': 63, 'def': 80, 'spd': 58, 'spc': 65, 'type1': 'WATER', 'type2': 'WATER'},
    "weedle": {'hp': 40, 'atk': 35, 'def': 30, 'spd': 50, 'spc': 20, 'type1': 'BUG', 'type2': 'POISON'},
    "weepinbell": {'hp': 65, 'atk': 90, 'def': 50, 'spd': 55, 'spc': 85, 'type1': 'GRASS', 'type2': 'POISON'},
    "weezing": {'hp': 65, 'atk': 90, 'def': 120, 'spd': 60, 'spc': 85, 'type1': 'POISON', 'type2': 'POISON'},
    "wigglytuff": {'hp': 140, 'atk': 70, 'def': 45, 'spd': 45, 'spc': 50, 'type1': 'NORMAL', 'type2': 'NORMAL'},
    "zapdos": {'hp': 90, 'atk': 90, 'def': 85, 'spd': 100, 'spc': 125, 'type1': 'ELECTRIC', 'type2': 'FLYING'},
    "zubat": {'hp': 40, 'atk': 45, 'def': 35, 'spd': 55, 'spc': 40, 'type1': 'POISON', 'type2': 'FLYING'}
}

MOVES_ID_TO_NAME = {
    -1: "NONE",
    0: "POUND",
    1: "KARATE_CHOP",
    2: "DOUBLESLAP",
    3: "COMET_PUNCH",
    4: "MEGA_PUNCH",
    5: "PAY_DAY",
    6: "FIRE_PUNCH",
    7: "ICE_PUNCH",
    8: "THUNDERPUNCH",
    9: "SCRATCH",
    10: "VICEGRIP",
    11: "GUILLOTINE",
    12: "RAZOR_WIND",
    13: "SWORDS_DANCE",
    14: "CUT",
    15: "GUST",
    16: "WING_ATTACK",
    17: "WHIRLWIND",
    18: "FLY",
    19: "BIND",
    20: "SLAM",
    21: "VINE_WHIP",
    22: "STOMP",
    23: "DOUBLE_KICK",
    24: "MEGA_KICK",
    25: "JUMP_KICK",
    26: "ROLLING_KICK",
    27: "SAND_ATTACK",
    28: "HEADBUTT",
    29: "HORN_ATTACK",
    30: "FURY_ATTACK",
    31: "HORN_DRILL",
    32: "TACKLE",
    33: "BODY_SLAM",
    34: "WRAP",
    35: "TAKE_DOWN",
    36: "THRASH",
    37: "DOUBLE_EDGE",
    38: "TAIL_WHIP",
    39: "POISON_STING",
    40: "TWINEEDLE",
    41: "PIN_MISSILE",
    42: "LEER",
    43: "BITE",
    44: "GROWL",
    45: "ROAR",
    46: "SING",
    47: "SUPERSONIC",
    48: "SONICBOOM",
    49: "DISABLE",
    50: "ACID",
    51: "EMBER",
    52: "FLAMETHROWER",
    53: "MIST",
    54: "WATER_GUN",
    55: "HYDRO_PUMP",
    56: "SURF",
    57: "ICE_BEAM",
    58: "BLIZZARD",
    59: "PSYBEAM",
    60: "BUBBLEBEAM",
    61: "AURORA_BEAM",
    62: "HYPER_BEAM",
    63: "PECK",
    64: "DRILL_PECK",
    65: "SUBMISSION",
    66: "LOW_KICK",
    67: "COUNTER",
    68: "SEISMIC_TOSS",
    69: "STRENGTH",
    70: "ABSORB",
    71: "MEGA_DRAIN",
    72: "LEECH_SEED",
    73: "GROWTH",
    74: "RAZOR_LEAF",
    75: "SOLARBEAM",
    76: "POISONPOWDER",
    77: "STUN_SPORE",
    78: "SLEEP_POWDER",
    79: "PETAL_DANCE",
    80: "STRING_SHOT",
    81: "DRAGON_RAGE",
    82: "FIRE_SPIN",
    83: "THUNDERSHOCK",
    84: "THUNDERBOLT",
    85: "THUNDER_WAVE",
    86: "THUNDER",
    87: "ROCK_THROW",
    88: "EARTHQUAKE",
    89: "FISSURE",
    90: "DIG",
    91: "TOXIC",
    92: "CONFUSION",
    93: "PSYCHIC_M",
    94: "HYPNOSIS",
    95: "MEDITATE",
    96: "AGILITY",
    97: "QUICK_ATTACK",
    98: "RAGE",
    99: "TELEPORT",
    100: "NIGHT_SHADE",
    101: "MIMIC",
    102: "SCREECH",
    103: "DOUBLE_TEAM",
    104: "RECOVER",
    105: "HARDEN",
    106: "MINIMIZE",
    107: "SMOKESCREEN",
    108: "CONFUSE_RAY",
    109: "WITHDRAW",
    110: "DEFENSE_CURL",
    111: "BARRIER",
    112: "LIGHT_SCREEN",
    113: "HAZE",
    114: "REFLECT",
    115: "FOCUS_ENERGY",
    116: "BIDE",
    117: "METRONOME",
    118: "MIRROR_MOVE",
    119: "SELFDESTRUCT",
    120: "EGG_BOMB",
    121: "LICK",
    122: "SMOG",
    123: "SLUDGE",
    124: "BONE_CLUB",
    125: "FIRE_BLAST",
    126: "WATERFALL",
    127: "CLAMP",
    128: "SWIFT",
    129: "SKULL_BASH",
    130: "SPIKE_CANNON",
    131: "CONSTRICT",
    132: "AMNESIA",
    133: "KINESIS",
    134: "SOFTBOILED",
    135: "HI_JUMP_KICK",
    136: "GLARE",
    137: "DREAM_EATER",
    138: "POISON_GAS",
    139: "BARRAGE",
    140: "LEECH_LIFE",
    141: "LOVELY_KISS",
    142: "SKY_ATTACK",
    143: "TRANSFORM",
    144: "BUBBLE",
    145: "DIZZY_PUNCH",
    146: "SPORE",
    147: "FLASH",
    148: "PSYWAVE",
    149: "SPLASH",
    150: "ACID_ARMOR",
    151: "CRABHAMMER",
    152: "EXPLOSION",
    153: "FURY_SWIPES",
    154: "BONEMERANG",
    155: "REST",
    156: "ROCK_SLIDE",
    157: "HYPER_FANG",
    158: "SHARPEN",
    159: "CONVERSION",
    160: "TRI_ATTACK",
    161: "SUPER_FANG",
    162: "SLASH",
    163: "SUBSTITUTE",
    164: "STRUGGLE"
}

NEW_MOVES_ID_TO_NAME = {key + 1: val for key, val in MOVES_ID_TO_NAME.items()}
MOVES_ID_TO_NAME = NEW_MOVES_ID_TO_NAME

MOVE_STATS = {
    "NONE": {'effect':'NO_ADDITIONAL_EFFECT', 'power':0, 'type':'BIRD', 'accuracy':0, 'pp':0},
    "POUND": {'effect': 'NO_ADDITIONAL_EFFECT', 'power': 40, 'type': 'NORMAL', 'accuracy': 100, 'pp': 35},
    "KARATE_CHOP": {'effect': 'NO_ADDITIONAL_EFFECT', 'power': 50, 'type': 'NORMAL', 'accuracy': 100, 'pp': 25},
    "DOUBLESLAP": {'effect': 'TWO_TO_FIVE_ATTACKS_EFFECT', 'power': 15, 'type': 'NORMAL', 'accuracy': 85, 'pp': 10},     
    "COMET_PUNCH": {'effect': 'TWO_TO_FIVE_ATTACKS_EFFECT', 'power': 18, 'type': 'NORMAL', 'accuracy': 85, 'pp': 15},    
    "MEGA_PUNCH": {'effect': 'NO_ADDITIONAL_EFFECT', 'power': 80, 'type': 'NORMAL', 'accuracy': 85, 'pp': 20},
    "PAY_DAY": {'effect': 'PAY_DAY_EFFECT', 'power': 40, 'type': 'NORMAL', 'accuracy': 100, 'pp': 20},
    "FIRE_PUNCH": {'effect': 'BURN_SIDE_EFFECT1', 'power': 75, 'type': 'FIRE', 'accuracy': 100, 'pp': 15},
    "ICE_PUNCH": {'effect': 'FREEZE_SIDE_EFFECT1', 'power': 75, 'type': 'ICE', 'accuracy': 100, 'pp': 15},
    "THUNDERPUNCH": {'effect': 'PARALYZE_SIDE_EFFECT1', 'power': 75, 'type': 'ELECTRIC', 'accuracy': 100, 'pp': 15},     
    "SCRATCH": {'effect': 'NO_ADDITIONAL_EFFECT', 'power': 40, 'type': 'NORMAL', 'accuracy': 100, 'pp': 35},
    "VICEGRIP": {'effect': 'NO_ADDITIONAL_EFFECT', 'power': 55, 'type': 'NORMAL', 'accuracy': 100, 'pp': 30},
    "GUILLOTINE": {'effect': 'OHKO_EFFECT', 'power': 1, 'type': 'NORMAL', 'accuracy': 30, 'pp': 5},
    "RAZOR_WIND": {'effect': 'CHARGE_EFFECT', 'power': 80, 'type': 'NORMAL', 'accuracy': 75, 'pp': 10},
    "SWORDS_DANCE": {'effect': 'ATTACK_UP2_EFFECT', 'power': 0, 'type': 'NORMAL', 'accuracy': 100, 'pp': 30},
    "CUT": {'effect': 'NO_ADDITIONAL_EFFECT', 'power': 50, 'type': 'NORMAL', 'accuracy': 95, 'pp': 30},
    "GUST": {'effect': 'NO_ADDITIONAL_EFFECT', 'power': 40, 'type': 'NORMAL', 'accuracy': 100, 'pp': 35},
    "WING_ATTACK": {'effect': 'NO_ADDITIONAL_EFFECT', 'power': 35, 'type': 'FLYING', 'accuracy': 100, 'pp': 35},
    "WHIRLWIND": {'effect': 'SWITCH_AND_TELEPORT_EFFECT', 'power': 0, 'type': 'NORMAL', 'accuracy': 85, 'pp': 20},       
    "FLY": {'effect': 'FLY_EFFECT', 'power': 70, 'type': 'FLYING', 'accuracy': 95, 'pp': 15},
    "BIND": {'effect': 'TRAPPING_EFFECT', 'power': 15, 'type': 'NORMAL', 'accuracy': 75, 'pp': 20},
    "SLAM": {'effect': 'NO_ADDITIONAL_EFFECT', 'power': 80, 'type': 'NORMAL', 'accuracy': 75, 'pp': 20},
    "VINE_WHIP": {'effect': 'NO_ADDITIONAL_EFFECT', 'power': 35, 'type': 'GRASS', 'accuracy': 100, 'pp': 10},
    "STOMP": {'effect': 'FLINCH_SIDE_EFFECT2', 'power': 65, 'type': 'NORMAL', 'accuracy': 100, 'pp': 20},
    "DOUBLE_KICK": {'effect': 'ATTACK_TWICE_EFFECT', 'power': 30, 'type': 'FIGHTING', 'accuracy': 100, 'pp': 30},        
    "MEGA_KICK": {'effect': 'NO_ADDITIONAL_EFFECT', 'power': 120, 'type': 'NORMAL', 'accuracy': 75, 'pp': 5},
    "JUMP_KICK": {'effect': 'JUMP_KICK_EFFECT', 'power': 70, 'type': 'FIGHTING', 'accuracy': 95, 'pp': 25},
    "ROLLING_KICK": {'effect': 'FLINCH_SIDE_EFFECT2', 'power': 60, 'type': 'FIGHTING', 'accuracy': 85, 'pp': 15},        
    "SAND_ATTACK": {'effect': 'ACCURACY_DOWN1_EFFECT', 'power': 0, 'type': 'NORMAL', 'accuracy': 100, 'pp': 15},
    "HEADBUTT": {'effect': 'FLINCH_SIDE_EFFECT2', 'power': 70, 'type': 'NORMAL', 'accuracy': 100, 'pp': 15},
    "HORN_ATTACK": {'effect': 'NO_ADDITIONAL_EFFECT', 'power': 65, 'type': 'NORMAL', 'accuracy': 100, 'pp': 25},
    "FURY_ATTACK": {'effect': 'TWO_TO_FIVE_ATTACKS_EFFECT', 'power': 15, 'type': 'NORMAL', 'accuracy': 85, 'pp': 20},    
    "HORN_DRILL": {'effect': 'OHKO_EFFECT', 'power': 1, 'type': 'NORMAL', 'accuracy': 30, 'pp': 5},
    "TACKLE": {'effect': 'NO_ADDITIONAL_EFFECT', 'power': 35, 'type': 'NORMAL', 'accuracy': 95, 'pp': 35},
    "BODY_SLAM": {'effect': 'PARALYZE_SIDE_EFFECT2', 'power': 85, 'type': 'NORMAL', 'accuracy': 100, 'pp': 15},
    "WRAP": {'effect': 'TRAPPING_EFFECT', 'power': 15, 'type': 'NORMAL', 'accuracy': 85, 'pp': 20},
    "TAKE_DOWN": {'effect': 'RECOIL_EFFECT', 'power': 90, 'type': 'NORMAL', 'accuracy': 85, 'pp': 20},
    "THRASH": {'effect': 'THRASH_PETAL_DANCE_EFFECT', 'power': 90, 'type': 'NORMAL', 'accuracy': 100, 'pp': 20},
    "DOUBLE_EDGE": {'effect': 'RECOIL_EFFECT', 'power': 100, 'type': 'NORMAL', 'accuracy': 100, 'pp': 15},
    "TAIL_WHIP": {'effect': 'DEFENSE_DOWN1_EFFECT', 'power': 0, 'type': 'NORMAL', 'accuracy': 100, 'pp': 30},
    "POISON_STING": {'effect': 'POISON_SIDE_EFFECT1', 'power': 15, 'type': 'POISON', 'accuracy': 100, 'pp': 35},
    "TWINEEDLE": {'effect': 'TWINEEDLE_EFFECT', 'power': 25, 'type': 'BUG', 'accuracy': 100, 'pp': 20},
    "PIN_MISSILE": {'effect': 'TWO_TO_FIVE_ATTACKS_EFFECT', 'power': 14, 'type': 'BUG', 'accuracy': 85, 'pp': 20},       
    "LEER": {'effect': 'DEFENSE_DOWN1_EFFECT', 'power': 0, 'type': 'NORMAL', 'accuracy': 100, 'pp': 30},
    "BITE": {'effect': 'FLINCH_SIDE_EFFECT1', 'power': 60, 'type': 'NORMAL', 'accuracy': 100, 'pp': 25},
    "GROWL": {'effect': 'ATTACK_DOWN1_EFFECT', 'power': 0, 'type': 'NORMAL', 'accuracy': 100, 'pp': 40},
    "ROAR": {'effect': 'SWITCH_AND_TELEPORT_EFFECT', 'power': 0, 'type': 'NORMAL', 'accuracy': 100, 'pp': 20},
    "SING": {'effect': 'SLEEP_EFFECT', 'power': 0, 'type': 'NORMAL', 'accuracy': 55, 'pp': 15},
    "SUPERSONIC": {'effect': 'CONFUSION_EFFECT', 'power': 0, 'type': 'NORMAL', 'accuracy': 55, 'pp': 20},
    "SONICBOOM": {'effect': 'SPECIAL_DAMAGE_EFFECT', 'power': 1, 'type': 'NORMAL', 'accuracy': 90, 'pp': 20},
    "DISABLE": {'effect': 'DISABLE_EFFECT', 'power': 0, 'type': 'NORMAL', 'accuracy': 55, 'pp': 20},
    "ACID": {'effect': 'DEFENSE_DOWN_SIDE_EFFECT', 'power': 40, 'type': 'POISON', 'accuracy': 100, 'pp': 30},
    "EMBER": {'effect': 'BURN_SIDE_EFFECT1', 'power': 40, 'type': 'FIRE', 'accuracy': 100, 'pp': 25},
    "FLAMETHROWER": {'effect': 'BURN_SIDE_EFFECT1', 'power': 95, 'type': 'FIRE', 'accuracy': 100, 'pp': 15},
    "MIST": {'effect': 'MIST_EFFECT', 'power': 0, 'type': 'ICE', 'accuracy': 100, 'pp': 30},
    "WATER_GUN": {'effect': 'NO_ADDITIONAL_EFFECT', 'power': 40, 'type': 'WATER', 'accuracy': 100, 'pp': 25},
    "HYDRO_PUMP": {'effect': 'NO_ADDITIONAL_EFFECT', 'power': 120, 'type': 'WATER', 'accuracy': 80, 'pp': 5},
    "SURF": {'effect': 'NO_ADDITIONAL_EFFECT', 'power': 95, 'type': 'WATER', 'accuracy': 100, 'pp': 15},
    "ICE_BEAM": {'effect': 'FREEZE_SIDE_EFFECT1', 'power': 95, 'type': 'ICE', 'accuracy': 100, 'pp': 10},
    "BLIZZARD": {'effect': 'FREEZE_SIDE_EFFECT1', 'power': 120, 'type': 'ICE', 'accuracy': 90, 'pp': 5},
    "PSYBEAM": {'effect': 'CONFUSION_SIDE_EFFECT', 'power': 65, 'type': 'PSYCHIC_TYPE', 'accuracy': 100, 'pp': 20},      
    "BUBBLEBEAM": {'effect': 'SPEED_DOWN_SIDE_EFFECT', 'power': 65, 'type': 'WATER', 'accuracy': 100, 'pp': 20},
    "AURORA_BEAM": {'effect': 'ATTACK_DOWN_SIDE_EFFECT', 'power': 65, 'type': 'ICE', 'accuracy': 100, 'pp': 20},
    "HYPER_BEAM": {'effect': 'HYPER_BEAM_EFFECT', 'power': 150, 'type': 'NORMAL', 'accuracy': 90, 'pp': 5},
    "PECK": {'effect': 'NO_ADDITIONAL_EFFECT', 'power': 35, 'type': 'FLYING', 'accuracy': 100, 'pp': 35},
    "DRILL_PECK": {'effect': 'NO_ADDITIONAL_EFFECT', 'power': 80, 'type': 'FLYING', 'accuracy': 100, 'pp': 20},
    "SUBMISSION": {'effect': 'RECOIL_EFFECT', 'power': 80, 'type': 'FIGHTING', 'accuracy': 80, 'pp': 25},
    "LOW_KICK": {'effect': 'FLINCH_SIDE_EFFECT2', 'power': 50, 'type': 'FIGHTING', 'accuracy': 90, 'pp': 20},
    "COUNTER": {'effect': 'NO_ADDITIONAL_EFFECT', 'power': 1, 'type': 'FIGHTING', 'accuracy': 100, 'pp': 20},
    "SEISMIC_TOSS": {'effect': 'SPECIAL_DAMAGE_EFFECT', 'power': 1, 'type': 'FIGHTING', 'accuracy': 100, 'pp': 20},      
    "STRENGTH": {'effect': 'NO_ADDITIONAL_EFFECT', 'power': 80, 'type': 'NORMAL', 'accuracy': 100, 'pp': 15},
    "ABSORB": {'effect': 'DRAIN_HP_EFFECT', 'power': 20, 'type': 'GRASS', 'accuracy': 100, 'pp': 20},
    "MEGA_DRAIN": {'effect': 'DRAIN_HP_EFFECT', 'power': 40, 'type': 'GRASS', 'accuracy': 100, 'pp': 10},
    "LEECH_SEED": {'effect': 'LEECH_SEED_EFFECT', 'power': 0, 'type': 'GRASS', 'accuracy': 90, 'pp': 10},
    "GROWTH": {'effect': 'SPECIAL_UP1_EFFECT', 'power': 0, 'type': 'NORMAL', 'accuracy': 100, 'pp': 40},
    "RAZOR_LEAF": {'effect': 'NO_ADDITIONAL_EFFECT', 'power': 55, 'type': 'GRASS', 'accuracy': 95, 'pp': 25},
    "SOLARBEAM": {'effect': 'CHARGE_EFFECT', 'power': 120, 'type': 'GRASS', 'accuracy': 100, 'pp': 10},
    "POISONPOWDER": {'effect': 'POISON_EFFECT', 'power': 0, 'type': 'POISON', 'accuracy': 75, 'pp': 35},
    "STUN_SPORE": {'effect': 'PARALYZE_EFFECT', 'power': 0, 'type': 'GRASS', 'accuracy': 75, 'pp': 30},
    "SLEEP_POWDER": {'effect': 'SLEEP_EFFECT', 'power': 0, 'type': 'GRASS', 'accuracy': 75, 'pp': 15},
    "PETAL_DANCE": {'effect': 'THRASH_PETAL_DANCE_EFFECT', 'power': 70, 'type': 'GRASS', 'accuracy': 100, 'pp': 20},     
    "STRING_SHOT": {'effect': 'SPEED_DOWN1_EFFECT', 'power': 0, 'type': 'BUG', 'accuracy': 95, 'pp': 40},
    "DRAGON_RAGE": {'effect': 'SPECIAL_DAMAGE_EFFECT', 'power': 1, 'type': 'DRAGON', 'accuracy': 100, 'pp': 10},
    "FIRE_SPIN": {'effect': 'TRAPPING_EFFECT', 'power': 15, 'type': 'FIRE', 'accuracy': 70, 'pp': 15},
    "THUNDERSHOCK": {'effect': 'PARALYZE_SIDE_EFFECT1', 'power': 40, 'type': 'ELECTRIC', 'accuracy': 100, 'pp': 30},     
    "THUNDERBOLT": {'effect': 'PARALYZE_SIDE_EFFECT1', 'power': 95, 'type': 'ELECTRIC', 'accuracy': 100, 'pp': 15},      
    "THUNDER_WAVE": {'effect': 'PARALYZE_EFFECT', 'power': 0, 'type': 'ELECTRIC', 'accuracy': 100, 'pp': 20},
    "THUNDER": {'effect': 'PARALYZE_SIDE_EFFECT1', 'power': 120, 'type': 'ELECTRIC', 'accuracy': 70, 'pp': 10},
    "ROCK_THROW": {'effect': 'NO_ADDITIONAL_EFFECT', 'power': 50, 'type': 'ROCK', 'accuracy': 65, 'pp': 15},
    "EARTHQUAKE": {'effect': 'NO_ADDITIONAL_EFFECT', 'power': 100, 'type': 'GROUND', 'accuracy': 100, 'pp': 10},
    "FISSURE": {'effect': 'OHKO_EFFECT', 'power': 1, 'type': 'GROUND', 'accuracy': 30, 'pp': 5},
    "DIG": {'effect': 'CHARGE_EFFECT', 'power': 100, 'type': 'GROUND', 'accuracy': 100, 'pp': 10},
    "TOXIC": {'effect': 'POISON_EFFECT', 'power': 0, 'type': 'POISON', 'accuracy': 85, 'pp': 10},
    "CONFUSION": {'effect': 'CONFUSION_SIDE_EFFECT', 'power': 50, 'type': 'PSYCHIC_TYPE', 'accuracy': 100, 'pp': 25},    
    "PSYCHIC_M": {'effect': 'SPECIAL_DOWN_SIDE_EFFECT', 'power': 90, 'type': 'PSYCHIC_TYPE', 'accuracy': 100, 'pp': 10}, 
    "HYPNOSIS": {'effect': 'SLEEP_EFFECT', 'power': 0, 'type': 'PSYCHIC_TYPE', 'accuracy': 60, 'pp': 20},
    "MEDITATE": {'effect': 'ATTACK_UP1_EFFECT', 'power': 0, 'type': 'PSYCHIC_TYPE', 'accuracy': 100, 'pp': 40},
    "AGILITY": {'effect': 'SPEED_UP2_EFFECT', 'power': 0, 'type': 'PSYCHIC_TYPE', 'accuracy': 100, 'pp': 30},
    "QUICK_ATTACK": {'effect': 'NO_ADDITIONAL_EFFECT', 'power': 40, 'type': 'NORMAL', 'accuracy': 100, 'pp': 30},        
    "RAGE": {'effect': 'RAGE_EFFECT', 'power': 20, 'type': 'NORMAL', 'accuracy': 100, 'pp': 20},
    "TELEPORT": {'effect': 'SWITCH_AND_TELEPORT_EFFECT', 'power': 0, 'type': 'PSYCHIC_TYPE', 'accuracy': 100, 'pp': 20}, 
    "NIGHT_SHADE": {'effect': 'SPECIAL_DAMAGE_EFFECT', 'power': 0, 'type': 'GHOST', 'accuracy': 100, 'pp': 15},
    "MIMIC": {'effect': 'MIMIC_EFFECT', 'power': 0, 'type': 'NORMAL', 'accuracy': 100, 'pp': 10},
    "SCREECH": {'effect': 'DEFENSE_DOWN2_EFFECT', 'power': 0, 'type': 'NORMAL', 'accuracy': 85, 'pp': 40},
    "DOUBLE_TEAM": {'effect': 'EVASION_UP1_EFFECT', 'power': 0, 'type': 'NORMAL', 'accuracy': 100, 'pp': 15},
    "RECOVER": {'effect': 'HEAL_EFFECT', 'power': 0, 'type': 'NORMAL', 'accuracy': 100, 'pp': 20},
    "HARDEN": {'effect': 'DEFENSE_UP1_EFFECT', 'power': 0, 'type': 'NORMAL', 'accuracy': 100, 'pp': 30},
    "MINIMIZE": {'effect': 'EVASION_UP1_EFFECT', 'power': 0, 'type': 'NORMAL', 'accuracy': 100, 'pp': 20},
    "SMOKESCREEN": {'effect': 'ACCURACY_DOWN1_EFFECT', 'power': 0, 'type': 'NORMAL', 'accuracy': 100, 'pp': 20},
    "CONFUSE_RAY": {'effect': 'CONFUSION_EFFECT', 'power': 0, 'type': 'GHOST', 'accuracy': 100, 'pp': 10},
    "WITHDRAW": {'effect': 'DEFENSE_UP1_EFFECT', 'power': 0, 'type': 'WATER', 'accuracy': 100, 'pp': 40},
    "DEFENSE_CURL": {'effect': 'DEFENSE_UP1_EFFECT', 'power': 0, 'type': 'NORMAL', 'accuracy': 100, 'pp': 40},
    "BARRIER": {'effect': 'DEFENSE_UP2_EFFECT', 'power': 0, 'type': 'PSYCHIC_TYPE', 'accuracy': 100, 'pp': 30},
    "LIGHT_SCREEN": {'effect': 'LIGHT_SCREEN_EFFECT', 'power': 0, 'type': 'PSYCHIC_TYPE', 'accuracy': 100, 'pp': 30},
    "HAZE": {'effect': 'HAZE_EFFECT', 'power': 0, 'type': 'ICE', 'accuracy': 100, 'pp': 30},
    "REFLECT": {'effect': 'REFLECT_EFFECT', 'power': 0, 'type': 'PSYCHIC_TYPE', 'accuracy': 100, 'pp': 20},
    "FOCUS_ENERGY": {'effect': 'FOCUS_ENERGY_EFFECT', 'power': 0, 'type': 'NORMAL', 'accuracy': 100, 'pp': 30},
    "BIDE": {'effect': 'BIDE_EFFECT', 'power': 0, 'type': 'NORMAL', 'accuracy': 100, 'pp': 10},
    "METRONOME": {'effect': 'METRONOME_EFFECT', 'power': 0, 'type': 'NORMAL', 'accuracy': 100, 'pp': 10},
    "MIRROR_MOVE": {'effect': 'MIRROR_MOVE_EFFECT', 'power': 0, 'type': 'FLYING', 'accuracy': 100, 'pp': 20},
    "SELFDESTRUCT": {'effect': 'EXPLODE_EFFECT', 'power': 130, 'type': 'NORMAL', 'accuracy': 100, 'pp': 5},
    "EGG_BOMB": {'effect': 'NO_ADDITIONAL_EFFECT', 'power': 100, 'type': 'NORMAL', 'accuracy': 75, 'pp': 10},
    "LICK": {'effect': 'PARALYZE_SIDE_EFFECT2', 'power': 20, 'type': 'GHOST', 'accuracy': 100, 'pp': 30},
    "SMOG": {'effect': 'POISON_SIDE_EFFECT2', 'power': 20, 'type': 'POISON', 'accuracy': 70, 'pp': 20},
    "SLUDGE": {'effect': 'POISON_SIDE_EFFECT2', 'power': 65, 'type': 'POISON', 'accuracy': 100, 'pp': 20},
    "BONE_CLUB": {'effect': 'FLINCH_SIDE_EFFECT1', 'power': 65, 'type': 'GROUND', 'accuracy': 85, 'pp': 20},
    "FIRE_BLAST": {'effect': 'BURN_SIDE_EFFECT2', 'power': 120, 'type': 'FIRE', 'accuracy': 85, 'pp': 5},
    "WATERFALL": {'effect': 'NO_ADDITIONAL_EFFECT', 'power': 80, 'type': 'WATER', 'accuracy': 100, 'pp': 15},
    "CLAMP": {'effect': 'TRAPPING_EFFECT', 'power': 35, 'type': 'WATER', 'accuracy': 75, 'pp': 10},
    "SWIFT": {'effect': 'SWIFT_EFFECT', 'power': 60, 'type': 'NORMAL', 'accuracy': 100, 'pp': 20},
    "SKULL_BASH": {'effect': 'CHARGE_EFFECT', 'power': 100, 'type': 'NORMAL', 'accuracy': 100, 'pp': 15},
    "SPIKE_CANNON": {'effect': 'TWO_TO_FIVE_ATTACKS_EFFECT', 'power': 20, 'type': 'NORMAL', 'accuracy': 100, 'pp': 15},  
    "CONSTRICT": {'effect': 'SPEED_DOWN_SIDE_EFFECT', 'power': 10, 'type': 'NORMAL', 'accuracy': 100, 'pp': 35},
    "AMNESIA": {'effect': 'SPECIAL_UP2_EFFECT', 'power': 0, 'type': 'PSYCHIC_TYPE', 'accuracy': 100, 'pp': 20},
    "KINESIS": {'effect': 'ACCURACY_DOWN1_EFFECT', 'power': 0, 'type': 'PSYCHIC_TYPE', 'accuracy': 80, 'pp': 15},        
    "SOFTBOILED": {'effect': 'HEAL_EFFECT', 'power': 0, 'type': 'NORMAL', 'accuracy': 100, 'pp': 10},
    "HI_JUMP_KICK": {'effect': 'JUMP_KICK_EFFECT', 'power': 85, 'type': 'FIGHTING', 'accuracy': 90, 'pp': 20},
    "GLARE": {'effect': 'PARALYZE_EFFECT', 'power': 0, 'type': 'NORMAL', 'accuracy': 75, 'pp': 30},
    "DREAM_EATER": {'effect': 'DREAM_EATER_EFFECT', 'power': 100, 'type': 'PSYCHIC_TYPE', 'accuracy': 100, 'pp': 15},    
    "POISON_GAS": {'effect': 'POISON_EFFECT', 'power': 0, 'type': 'POISON', 'accuracy': 55, 'pp': 40},
    "BARRAGE": {'effect': 'TWO_TO_FIVE_ATTACKS_EFFECT', 'power': 15, 'type': 'NORMAL', 'accuracy': 85, 'pp': 20},        
    "LEECH_LIFE": {'effect': 'DRAIN_HP_EFFECT', 'power': 20, 'type': 'BUG', 'accuracy': 100, 'pp': 15},
    "LOVELY_KISS": {'effect': 'SLEEP_EFFECT', 'power': 0, 'type': 'NORMAL', 'accuracy': 75, 'pp': 10},
    "SKY_ATTACK": {'effect': 'CHARGE_EFFECT', 'power': 140, 'type': 'FLYING', 'accuracy': 90, 'pp': 5},
    "TRANSFORM": {'effect': 'TRANSFORM_EFFECT', 'power': 0, 'type': 'NORMAL', 'accuracy': 100, 'pp': 10},
    "BUBBLE": {'effect': 'SPEED_DOWN_SIDE_EFFECT', 'power': 20, 'type': 'WATER', 'accuracy': 100, 'pp': 30},
    "DIZZY_PUNCH": {'effect': 'NO_ADDITIONAL_EFFECT', 'power': 70, 'type': 'NORMAL', 'accuracy': 100, 'pp': 10},
    "SPORE": {'effect': 'SLEEP_EFFECT', 'power': 0, 'type': 'GRASS', 'accuracy': 100, 'pp': 15},
    "FLASH": {'effect': 'ACCURACY_DOWN1_EFFECT', 'power': 0, 'type': 'NORMAL', 'accuracy': 70, 'pp': 20},
    "PSYWAVE": {'effect': 'SPECIAL_DAMAGE_EFFECT', 'power': 1, 'type': 'PSYCHIC_TYPE', 'accuracy': 80, 'pp': 15},        
    "SPLASH": {'effect': 'SPLASH_EFFECT', 'power': 0, 'type': 'NORMAL', 'accuracy': 100, 'pp': 40},
    "ACID_ARMOR": {'effect': 'DEFENSE_UP2_EFFECT', 'power': 0, 'type': 'POISON', 'accuracy': 100, 'pp': 40},
    "CRABHAMMER": {'effect': 'NO_ADDITIONAL_EFFECT', 'power': 90, 'type': 'WATER', 'accuracy': 85, 'pp': 10},
    "EXPLOSION": {'effect': 'EXPLODE_EFFECT', 'power': 170, 'type': 'NORMAL', 'accuracy': 100, 'pp': 5},
    "FURY_SWIPES": {'effect': 'TWO_TO_FIVE_ATTACKS_EFFECT', 'power': 18, 'type': 'NORMAL', 'accuracy': 80, 'pp': 15},    
    "BONEMERANG": {'effect': 'ATTACK_TWICE_EFFECT', 'power': 50, 'type': 'GROUND', 'accuracy': 90, 'pp': 10},
    "REST": {'effect': 'HEAL_EFFECT', 'power': 0, 'type': 'PSYCHIC_TYPE', 'accuracy': 100, 'pp': 10},
    "ROCK_SLIDE": {'effect': 'NO_ADDITIONAL_EFFECT', 'power': 75, 'type': 'ROCK', 'accuracy': 90, 'pp': 10},
    "HYPER_FANG": {'effect': 'FLINCH_SIDE_EFFECT1', 'power': 80, 'type': 'NORMAL', 'accuracy': 90, 'pp': 15},
    "SHARPEN": {'effect': 'ATTACK_UP1_EFFECT', 'power': 0, 'type': 'NORMAL', 'accuracy': 100, 'pp': 30},
    "CONVERSION": {'effect': 'CONVERSION_EFFECT', 'power': 0, 'type': 'NORMAL', 'accuracy': 100, 'pp': 30},
    "TRI_ATTACK": {'effect': 'NO_ADDITIONAL_EFFECT', 'power': 80, 'type': 'NORMAL', 'accuracy': 100, 'pp': 10},
    "SUPER_FANG": {'effect': 'SUPER_FANG_EFFECT', 'power': 1, 'type': 'NORMAL', 'accuracy': 90, 'pp': 10},
    "SLASH": {'effect': 'NO_ADDITIONAL_EFFECT', 'power': 70, 'type': 'NORMAL', 'accuracy': 100, 'pp': 20},
    "SUBSTITUTE": {'effect': 'SUBSTITUTE_EFFECT', 'power': 0, 'type': 'NORMAL', 'accuracy': 100, 'pp': 10},
    "STRUGGLE": {'effect': 'RECOIL_EFFECT', 'power': 50, 'type': 'NORMAL', 'accuracy': 100, 'pp': 10}
}

MOVE_EFFECT_TO_ID = {
    'SLEEP_EFFECT': 0,
    'POISON_EFFECT': 1,
    'DRAIN_HP_EFFECT': 2,
    'BURN_SIDE_EFFECT1': 3,
    'FREEZE_SIDE_EFFECT1': 4,
    'PARALYZE_SIDE_EFFECT1': 5,
    'EXPLODE_EFFECT': 6,
    'DREAM_EATER_EFFECT': 7,
    'MIRROR_MOVE_EFFECT': 8,
    'ATTACK_UP1_EFFECT': 9,
    'DEFENSE_UP1_EFFECT': 10,
    'SPEED_UP1_EFFECT': 11,
    'SPECIAL_UP1_EFFECT': 12,
    'ACCURACY_UP1_EFFECT': 13,
    'EVASION_UP1_EFFECT': 14,
    'PAY_DAY_EFFECT': 15,
    'SWIFT_EFFECT': 16,
    'ATTACK_DOWN1_EFFECT': 17,
    'DEFENSE_DOWN1_EFFECT': 18,
    'SPEED_DOWN1_EFFECT': 19,
    'SPECIAL_DOWN1_EFFECT': 20,
    'ACCURACY_DOWN1_EFFECT': 21,
    'EVASION_DOWN1_EFFECT': 22,
    'CONVERSION_EFFECT': 23,
    'HAZE_EFFECT': 24,
    'BIDE_EFFECT': 25,
    'THRASH_PETAL_DANCE_EFFECT': 26,
    'SWITCH_AND_TELEPORT_EFFECT': 27,
    'TWO_TO_FIVE_ATTACKS_EFFECT': 28,
    'FLINCH_SIDE_EFFECT1': 29,
    'SLEEP_EFFECT': 30,
    'POISON_SIDE_EFFECT2': 31,
    'BURN_SIDE_EFFECT2': 32,
    'PARALYZE_SIDE_EFFECT2': 33,
    'FLINCH_SIDE_EFFECT2': 34,
    'OHKO_EFFECT': 35,
    'CHARGE_EFFECT': 36,
    'SUPER_FANG_EFFECT': 37,
    'SPECIAL_DAMAGE_EFFECT': 38,
    'TRAPPING_EFFECT': 39,
    'FLY_EFFECT': 40,
    'ATTACK_TWICE_EFFECT': 41,
    'JUMP_KICK_EFFECT': 42,
    'MIST_EFFECT': 43,
    'FOCUS_ENERGY_EFFECT': 44,
    'RECOIL_EFFECT': 45,
    'CONFUSION_EFFECT': 46,
    'ATTACK_UP2_EFFECT': 47,
    'DEFENSE_UP2_EFFECT': 48,
    'SPEED_UP2_EFFECT': 49,
    'SPECIAL_UP2_EFFECT': 50,
    'ACCURACY_UP2_EFFECT': 51,
    'EVASION_UP2_EFFECT': 52,
    'HEAL_EFFECT': 53,
    'TRANSFORM_EFFECT': 54,
    'ATTACK_DOWN2_EFFECT': 55,
    'DEFENSE_DOWN2_EFFECT': 56,
    'SPEED_DOWN2_EFFECT': 57,
    'SPECIAL_DOWN2_EFFECT': 58,
    'ACCURACY_DOWN2_EFFECT': 59,
    'EVASION_DOWN2_EFFECT': 60,
    'LIGHT_SCREEN_EFFECT': 61,
    'REFLECT_EFFECT': 62,
    'POISON_EFFECT': 63,
    'PARALYZE_EFFECT': 64,
    'ATTACK_DOWN_SIDE_EFFECT': 65,
    'DEFENSE_DOWN_SIDE_EFFECT': 66,
    'SPEED_DOWN_SIDE_EFFECT': 67,
    'SPECIAL_DOWN_SIDE_EFFECT': 68,
    'CONFUSION_SIDE_EFFECT': 69,
    'TWINEEDLE_EFFECT': 70,
    'SUBSTITUTE_EFFECT': 71,
    'HYPER_BEAM_EFFECT': 72,
    'RAGE_EFFECT': 73,
    'MIMIC_EFFECT': 74,
    'METRONOME_EFFECT': 75,
    'LEECH_SEED_EFFECT': 76,
    'SPLASH_EFFECT': 77,
    'DISABLE_EFFECT': 78,
    'NO_ADDITIONAL_EFFECT': 79
}

MAP_LABELS = {
    0: 'PALLET TOWN', 
    1: 'VIRIDIAN CITY', 
    2: 'PEWTER CITY', 
    3: 'CERULEAN CITY', 
    4: 'LAVENDER TOWN', 
    5: 'VERMILION CITY', 
    6: 'CELADON CITY', 
    7: 'FUCHSIA CITY', 
    8: 'CINNABAR ISLAND', 
    9: 'INDIGO PLATEAU', 
    10: 'SAFFRON CITY', 
    11: 'ROUTE 1', 
    12: 'ROUTE 2', 
    13: 'ROUTE 3', 
    14: 'ROUTE 4', 
    15: 'ROUTE 5', 
    16: 'ROUTE 6', 
    17: 'ROUTE 7', 
    18: 'ROUTE 8', 
    19: 'ROUTE 9', 
    20: 'ROUTE 10', 
    21: 'ROUTE 11', 
    22: 'ROUTE 12', 
    23: 'ROUTE 13', 
    24: 'ROUTE 14', 
    25: 'ROUTE 15', 
    26: 'ROUTE 16', 
    27: 'ROUTE 17', 
    28: 'ROUTE 18', 
    29: 'SEA ROUTE 19', 
    30: 'SEA ROUTE 20', 
    31: 'SEA ROUTE 21', 
    32: 'ROUTE 22', 
    33: 'ROUTE 23', 
    34: 'ROUTE 24', 
    35: 'ROUTE 25', 
    36: 'VIRIDIAN FOREST', 
    37: 'MT.MOON', 
    38: 'ROCK TUNNEL', 
    39: 'SEA COTTAGE', 
    40: 'S.S.ANNE', 
    41: '#MON LEAGUE', 
    42: 'UNDERGROUND PATH', 
    43: '#MON TOWER', 
    44: 'SEAFOAM ISLANDS', 
    45: 'VICTORY ROAD', 
    46: "DIGLETT's CAVE", 
    47: 'ROCKET HQ', 
    48: 'SILPH CO.', 
    49: '<PKMN> MANSION', 
    50: 'SAFARI ZONE', 
    51: 'CERULEAN CAVE', 
    52: 'POWER PLANT'
}

TYPE_MATCHUP = {
    ('WATER', 'FIRE'): "SUPER_EFFECTIVE",
    ('FIRE', 'GRASS'): "SUPER_EFFECTIVE",
    ('FIRE', 'ICE'): "SUPER_EFFECTIVE",
    ('GRASS', 'WATER'): "SUPER_EFFECTIVE",
    ('ELECTRIC', 'WATER'): "SUPER_EFFECTIVE",
    ('WATER', 'ROCK'): "SUPER_EFFECTIVE",
    ('GROUND', 'FLYING'): "NO_EFFECT",
    ('WATER', 'WATER'): "NOT_VERY_EFFECTIVE",
    ('FIRE', 'FIRE'): "NOT_VERY_EFFECTIVE",
    ('ELECTRIC', 'ELECTRIC'): "NOT_VERY_EFFECTIVE",
    ('ICE', 'ICE'): "NOT_VERY_EFFECTIVE",
    ('GRASS', 'GRASS'): "NOT_VERY_EFFECTIVE",
    ('PSYCHIC_TYPE', 'PSYCHIC_TYPE'): "NOT_VERY_EFFECTIVE",
    ('FIRE', 'WATER'): "NOT_VERY_EFFECTIVE",
    ('GRASS', 'FIRE'): "NOT_VERY_EFFECTIVE",
    ('WATER', 'GRASS'): "NOT_VERY_EFFECTIVE",
    ('ELECTRIC', 'GRASS'): "NOT_VERY_EFFECTIVE",
    ('NORMAL', 'ROCK'): "NOT_VERY_EFFECTIVE",
    ('NORMAL', 'GHOST'): "NO_EFFECT",
    ('GHOST', 'GHOST'): "SUPER_EFFECTIVE",
    ('FIRE', 'BUG'): "SUPER_EFFECTIVE",
    ('FIRE', 'ROCK'): "NOT_VERY_EFFECTIVE",
    ('WATER', 'GROUND'): "SUPER_EFFECTIVE",
    ('ELECTRIC', 'GROUND'): "NO_EFFECT",
    ('ELECTRIC', 'FLYING'): "SUPER_EFFECTIVE",
    ('GRASS', 'GROUND'): "SUPER_EFFECTIVE",
    ('GRASS', 'BUG'): "NOT_VERY_EFFECTIVE",
    ('GRASS', 'POISON'): "NOT_VERY_EFFECTIVE",
    ('GRASS', 'ROCK'): "SUPER_EFFECTIVE",
    ('GRASS', 'FLYING'): "NOT_VERY_EFFECTIVE",
    ('ICE', 'WATER'): "NOT_VERY_EFFECTIVE",
    ('ICE', 'GRASS'): "SUPER_EFFECTIVE",
    ('ICE', 'GROUND'): "SUPER_EFFECTIVE",
    ('ICE', 'FLYING'): "SUPER_EFFECTIVE",
    ('FIGHTING', 'NORMAL'): "SUPER_EFFECTIVE",
    ('FIGHTING', 'POISON'): "NOT_VERY_EFFECTIVE",
    ('FIGHTING', 'FLYING'): "NOT_VERY_EFFECTIVE",
    ('FIGHTING', 'PSYCHIC_TYPE'): "NOT_VERY_EFFECTIVE",
    ('FIGHTING', 'BUG'): "NOT_VERY_EFFECTIVE",
    ('FIGHTING', 'ROCK'): "SUPER_EFFECTIVE",
    ('FIGHTING', 'ICE'): "SUPER_EFFECTIVE",
    ('FIGHTING', 'GHOST'): "NO_EFFECT",
    ('POISON', 'GRASS'): "SUPER_EFFECTIVE",
    ('POISON', 'POISON'): "NOT_VERY_EFFECTIVE",
    ('POISON', 'GROUND'): "NOT_VERY_EFFECTIVE",
    ('POISON', 'BUG'): "SUPER_EFFECTIVE",
    ('POISON', 'ROCK'): "NOT_VERY_EFFECTIVE",
    ('POISON', 'GHOST'): "NOT_VERY_EFFECTIVE",
    ('GROUND', 'FIRE'): "SUPER_EFFECTIVE",
    ('GROUND', 'ELECTRIC'): "SUPER_EFFECTIVE",
    ('GROUND', 'GRASS'): "NOT_VERY_EFFECTIVE",
    ('GROUND', 'BUG'): "NOT_VERY_EFFECTIVE",
    ('GROUND', 'ROCK'): "SUPER_EFFECTIVE",
    ('GROUND', 'POISON'): "SUPER_EFFECTIVE",
    ('FLYING', 'ELECTRIC'): "NOT_VERY_EFFECTIVE",
    ('FLYING', 'FIGHTING'): "SUPER_EFFECTIVE",
    ('FLYING', 'BUG'): "SUPER_EFFECTIVE",
    ('FLYING', 'GRASS'): "SUPER_EFFECTIVE",
    ('FLYING', 'ROCK'): "NOT_VERY_EFFECTIVE",
    ('PSYCHIC_TYPE', 'FIGHTING'): "SUPER_EFFECTIVE",
    ('PSYCHIC_TYPE', 'POISON'): "SUPER_EFFECTIVE",
    ('BUG', 'FIRE'): "NOT_VERY_EFFECTIVE",
    ('BUG', 'GRASS'): "SUPER_EFFECTIVE",
    ('BUG', 'FIGHTING'): "NOT_VERY_EFFECTIVE",
    ('BUG', 'FLYING'): "NOT_VERY_EFFECTIVE",
    ('BUG', 'PSYCHIC_TYPE'): "SUPER_EFFECTIVE",
    ('BUG', 'GHOST'): "NOT_VERY_EFFECTIVE",
    ('BUG', 'POISON'): "SUPER_EFFECTIVE",
    ('ROCK', 'FIRE'): "SUPER_EFFECTIVE",
    ('ROCK', 'FIGHTING'): "NOT_VERY_EFFECTIVE",
    ('ROCK', 'GROUND'): "NOT_VERY_EFFECTIVE",
    ('ROCK', 'FLYING'): "SUPER_EFFECTIVE",
    ('ROCK', 'BUG'): "SUPER_EFFECTIVE",
    ('ROCK', 'ICE'): "SUPER_EFFECTIVE",
    ('GHOST', 'NORMAL'): "NO_EFFECT",
    ('GHOST', 'PSYCHIC_TYPE'): "NO_EFFECT",
    ('FIRE', 'DRAGON'): "NOT_VERY_EFFECTIVE",
    ('WATER', 'DRAGON'): "NOT_VERY_EFFECTIVE",
    ('ELECTRIC', 'DRAGON'): "NOT_VERY_EFFECTIVE",
    ('GRASS', 'DRAGON'): "NOT_VERY_EFFECTIVE",
    ('ICE', 'DRAGON'): "SUPER_EFFECTIVE",
    ('DRAGON', 'DRAGON'): "SUPER_EFFECTIVE"
}

TYPE_EFFECTIVENESS = {
    "SUPER_EFFECTIVE": 2,
    "EFFECTIVE": 1,
    "NOT_VERY_EFFECTIVE": 0.5,
    "NO_EFFECT": 0
}

POSITION_LABEL = {
    (3, 6, 38):"StartingPos",
    (7, 1, 38):"ExitRoom",
    (2, 8, 37):"ExitHome",
    (3, 8, 37):"ExitHome",
    (10,3, 0 ):"EnterRoad1",
    (11,3, 0 ):"EnterRoad1",
    (7, 4, 40):"Squirtle",
    (10,0, 12):"ExitRoad1",
    (11,0, 12):"ExitRoad1",
    (29,20, 1):"MartEntrance"
}

TYPES_NAME_TO_ID = {
    "NORMAL": 0,
    'FIGHTING': 1,
    "FLYING": 2,
    "POISON": 3,
    "FIRE": 4,
    "WATER": 5,
    "GRASS": 6,
    "ELECTRIC": 7,
    "PSYCHIC_TYPE": 8,
    "ICE": 9,
    "GROUND": 10,
    "ROCK": 11,
    "BIRD": 12,
    "BUG": 13,
    "GHOTS": 14,
    "DRAGON": 15
}

TYPES_ID_TO_NAME = {v: k for k, v in TYPES_NAME_TO_ID.items()}